### ISSUE TITLE
子元素继承父元素的透明度的解决方法

### ISSUE THREAD

**Issue by gdutwyg** [gdutwyg/frontEnd-notes#28]
今天在做移动端蒙层的时候遇到了子元素继承父元素的透明度（opacity）的情况

问题重现： 
```css
.opacity {
    background: #000;
    opacity：0.7
} 
```
这种写法就算给子元素opacity_child重新赋值`opacity: 1`；他也同样会继承父元素opacity的值。 

正确写法： 
```css
.opacity { 
    background: rgba(0,0,0, .7);
}
```
