### ISSUE TITLE
ios 低版本(比如ios8)的一些踩坑

### ISSUE THREAD

**Issue by gdutwyg** [gdutwyg/frontEnd-notes#52]
* 比如不支持new Date('2019-1-17')
```js
new Date('2019-1-7') // invalid value
new Date('2019/1/7') // 正解
```
ios 支持以下格式
* ~yyyy-MM-dd~
* yyyy/MM/dd
* MM/dd/yyyy
* MMMM dd, yyyy
* MMM dd, yyyy

[参考](https://www.cnblogs.com/zldream1106/p/3657217.html)

* 低版本ios css3的特性要加**-webkit-**前缀
```css
{
  transform: translateX(-50%);
  -webkit-transform: translateX(-50%);
}
```
