### ISSUE TITLE
background简写方式

### ISSUE THREAD

**Issue by gdutwyg** [gdutwyg/frontEnd-notes#63]
简写方式：
```js
background: [background-color] [background-image] [background-repeat] [background-attachment] [background-position] / [ background-size] [background-origin] [background-clip];
```
```css
/* demo */
.body {
 background: blueviolet url(./imgs/bg.jpg) no-repeat center / 100% 100% padding-box padding-box;
}
```
> background-position与background-size 之间要有`/`,否则会不生效

各个属性：
* background-color: 指定背景颜色
* background-image: 设置背景图像, 可以是真实的图片路径, 也可以是创建的渐变背景;
* background-repeat: 指定背景图像的铺排方式（值有`repeat-x`,`repeat-y`, `no-repeat`, `repeat`(默认）;
* background-attachment: 指定背景图像是滚动还是固定（值有fixed, scroll(默认)）;
* background-position: 设置背景图像的位置(默认值: 0% 0%,, 等同于left top);
* background-size: 设置背景图像的大小(length（像素）|percentage（百分比）|cover|contain|auto（默认）);
* background-origin: 设置背景图像显示的原点[background-position相对定位的原点(值有`border-box`, `content-box`, `padding-box`(默认));
* background-clip: 设置背景图像向外剪裁的区域(值有`border-box`(默认), `content-box`, `padding-box`);
